server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/userdb
    username: root
    password: Goodluck@124
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true
