server:
  port: 8761

spring:
  application:
    name: discovery-service

  cloud:
    gateway:
      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # USER SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

    registryFetchIntervalSeconds: 5